name: Docker CI

on:
  push:
    branches: ["master"]
  workflow_dispatch:

jobs:
  docker:
    runs-on: 'ubuntu-latest'
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.APP_DOCKER_USERNAME }}
          password: ${{ secrets.APP_DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t mrepol742/phpspa-example:latest .

      - name: Push Docker image
        run: |
          docker push mrepol742/phpspa-example:latest

      - name: Run Docker container
        run: |
          docker run -d -p 8080:80 --name phpspa-example mrepol742/phpspa-example:latest

      - name: Check container logs
        run: |
          docker logs phpspa-example

      - name: Stop and remove container
        if: always()
        run: |
          docker stop phpspa-example
          docker rm phpspa-example